version: "2"

services:
  web:
    image: lambyte/lapx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      #- ./src/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
    environment:
      XDEBUG_CONFIG: remote_host=

    links:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data:/var/lib/mysql